version: '3'

services:
  web:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./www:/var/www/laravel
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - db
      - php
      - cache
    networks:
      - backend

  php:
    build:
      dockerfile: ./dockerfiles/php.Dockerfile
    volumes:
      - ./www:/var/www/laravel
    restart: always
    ports:
      - "9000:9000"
    networks:
      - backend

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./configs/mysql/.env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  cache:
    image: redis:8.0-M03
    volumes:
      - cache-data:/data
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

  cache-data:
    driver: local